name: geovaz_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  http: ^1.5.0
  location: ^8.0.1
  lucide_icons_flutter: ^3.1.5
  flutter_screenutil: ^5.9.3
  get_it: ^9.0.5
  dio: ^5.9.0
  result_dart: ^2.1.1
  freezed: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.1
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
